ALTER TABLE public.meningite_cases
  ADD COLUMN IF NOT EXISTS faixa_etaria text,
  ADD COLUMN IF NOT EXISTS regional text,
  ADD COLUMN IF NOT EXISTS macroregiao text;

UPDATE public.meningite_cases
SET idade = date_part('year', age(current_date, data_nascimento))
WHERE data_nascimento IS NOT NULL AND idade IS NULL;

UPDATE public.meningite_cases
SET faixa_etaria = CASE
  WHEN idade < 1 THEN '< 1 ano'
  WHEN idade <= 10 THEN '1 a 10 anos'
  WHEN idade <= 20 THEN '11 a 20 anos'
  WHEN idade <= 30 THEN '21 a 30 anos'
  WHEN idade <= 40 THEN '31 a 40 anos'
  WHEN idade <= 50 THEN '41 a 50 anos'
  WHEN idade <= 60 THEN '51 a 60 anos'
  WHEN idade <= 70 THEN '61 a 70 anos'
  ELSE 'Acima de 70 anos' END
WHERE idade IS NOT NULL AND faixa_etaria IS NULL;

WITH r(reg, macro, muns) AS (VALUES
('ACAILANDIA','MACROREGIÃO SUL','ACAILANDIA|BOM JESUS DAS SELVAS|BURITICUPU|CIDELANDIA|ITINGA DO MARANHAO|SAO FRANCISCO DO BREJAO|SAO PEDRO DA AGUA BRANCA|VILA NOVA DOS MARTIRIOS'),
('CAXIAS','MACROREGIÃO LESTE','AFONSO CUNHA|ALDEIAS ALTAS|BURITI|CAXIAS|COELHO NETO|DUQUE BACELAR|SAO JOAO DO SOTER'),
('CHAPADINHA','MACROREGIÃO NORTE','AGUA DOCE DO MARANHAO|ANAPURUS|ARAIOSES|BREJO|CHAPADINHA|MAGALHAES DE ALMEIDA|MATA ROMA|MILAGRES DO MARANHAO|PAULINO NEVES|SANTA QUITERIA DO MARANHAO|SANTANA DO MARANHAO|SAO BERNARDO|TUTOIA'),
('METROPOLITANA','MACROREGIÃO NORTE','ALCANTARA|PACO DO LUMIAR|RAPOSA|SAO J. DE RIBAMAR|SAO JOSE DE RIBAMAR|SAO LUIS'),
('BACABAL','MACROREGIÃO NORTE','ALTAMIRA DO MARANHAO|BACABAL|BOM LUGAR|BREJO DE AREIA|CONCEICAO DO LAGO-ACU|LAGO VERDE|MARAJA DO SENA|MARAJA DO SENA *|OLHO D''AGUA DAS CUNHAS|OLHO D´AGUA DAS CUNHAS|PAULO RAMOS|SAO LUIS GONZAGA DO MARANHAO|SAO LUIZ GONZAGA DO MARANHAO|VITORINO FREIRE'),
('CODO','MACROREGIÃO LESTE','ALTO ALEGRE|ALTO ALEGRE DO MARANHAO|CODO|COROATA|PERITORO|SAO MATEUS|SAO MATEUS DO MARANHAO|TIMBIRAS'),
('SANTA INÊS','MACROREGIÃO NORTE','ALTO ALEGRE DO PINDARE|BELA  VISTA|BELA VISTA DO MARANHAO|BOM JARDIM|GOVERNADOR NEWTON BELLO|IGARAPE DO MEIO|MONCAO|PINDARE|PINDARE-MIRIM|PIO XII|SANTA INES|SANTA LUZIA|SAO JOAO DO CARU|SATUBINHA|TUFILANDIA'),
('BALSAS','MACROREGIÃO SUL','ALTO PARNAIBA|BALSAS|FEIRA NOVA DO MARANHAO|FORMOSA DA SERRA NEGRA|FORTALEZA DOS NOGUEIRAS|LORETO|NOVA COLINAS|RIACHAO|SAMBAIBA|SAO FELIX DE BALSAS|SAO PEDRO DOS CRENTES|SAO RAIMUNDO DAS MANGABEIRAS|TASSO FRAGOSO'),
('ZE DOCA','MACROREGIÃO NORTE','AMAPA DO MARANHAO|ARAGUANA|BOA VISTA DO GURUPI|CANDIDO MENDES|CARUTAPERA|CENTRO DO GUILHERME|CENTRO NOVO DO MARANHAO|GODOFREDO VIANA|GOVERNADOR NUNES FREIRE|JUNCO DO MARANHAO|LUIS DOMINGUES|MARACACUME|MARANHAOZINHO|NOVA OLINDA DO MARANHAO|PRESIDENTE MEDICI|SANTA LUZIA DO PARUA|ZE DOCA'),
('IMPERATRIZ','MACROREGIÃO SUL','AMARANTE|AMARANTE DO MARANHAO|BURITIRANA|CAMPESTRE DO MARANHAO|CAROLINA|DAVINOPOLIS|ESTREITO|GOV. EDSON LOBAO|GOVERNADOR EDISON LOBAO|IMPERATRIZ|JOAO LISBOA|LAJEADO NOVO|MONTES ALTOS|PORTO FRANCO|RIBAMAR FIQUENE|SAO JOAO DO PARAISO|SENADOR LA ROCQUE|SENADOR LA ROQUE|SITIO NOVO'),
('ITAPECURU','MACROREGIÃO NORTE','ANAJATUBA|ARARI|BELAGUA|CANTANHEDE|ITAPECURU MIRIM|MATOES DO NORTE|MIRANDA DO NORTE|NINA RODRIGUES|PIRAPEMAS|PRESIDENTE VARGAS|SAO BENEDITO DO RIO PRETO|URBANO SANTOS|VARGEM GRANDE|VITORIA DO MEARIM'),
('PINHEIRO','MACROREGIÃO NORTE','APICUM-ACU|BACURI|BEQUIMAO|CEDRAL|CENTRAL DO MARANHAO|CURURUPU|GUIMARAES|MIRINZAL|PEDRO DO ROSARIO|PERI MIRIM|PERIMIRIM|PINHEIRO|PORTO RICO DO MARANHAO|PRESIDENTE SARNEY|SANTA HELENA|SERRANO DO MARANHAO|TURIACU|TURILANDIA'),
('BARRA DO CORDA','MACROREGIÃO SUL','ARAME|BARRA DO CORDA|FERNANDO FALCAO|GENIPAPO DOS VIEIRAS|GRAJAU|ITAIPAVA DO GRAJAU|JENIPAPO DOS VIEIRAS'),
('ROSÁRIO','MACROREGIÃO NORTE','AXIXA|BACABEIRA|BARREIRINHAS|CACHOEIRA GRANDE|HUMBERTO DE CAMPOS|ICATU|MORROS|PRESIDENTE JUSCELINO|PRIMEIRA CRUZ|ROSARIO|SANTA RITA|SANTO AMARO|SANTO AMARO DO MARANHAO'),
('VIANA','MACROREGIÃO NORTE','BACURITUBA|CAJAPIO|CAJARI|MATINHA|OLINDA NOVA DO MARANHAO|PALMEIRANDIA|PENALVA|SAO BENTO|SAO JOAO BATISTA|SAO VICENTE FERRER|VIANA'),
('S.J. DOS PATOS','MACROREGIÃO LESTE','BARAO DE GRAJAU|BENEDITO LEITE|BURITI BRAVO|COLINAS|JATOBA|LAGOA DO MATO|MIRADOR|NOVA IORQUE|PARAIBANO|PASSAGEM FRANCA|PASTOS BONS|SAO DOMINGOS DO AZEITAO|SAO JOAO DOS PATOS|SUCUPIRA DO NORTE|SUCUPIRA DO RIACHAO'),
('OUTRO EST.','OUTROS ESTADOS','BELEM|OUTROS|RONDON DO PARA'),
('PEDREIRAS','MACROREGIÃO LESTE','BERNARDO DO MEARIM|ESPERANTINOPOLIS|IGARAPE GRANDE|LAGO DA PEDRA|LAGO DO JUNCO|LAGO DOS RODRIGUES|LAGOA GRANDE DO MA|LAGOA GRANDE DO MARANHAO|LIMA CAMPOS|PEDREIRAS|POCAO DE PEDRAS|SAO RAIMUNDO DO DOCA BEZERRA|SAO RDO DO DOCA BEZERRA|SAO ROBERTO|TRIZIDELA DO VALE'),
('PRESIDENTE DUTRA','MACROREGIÃO LESTE','CAPINZAL DO NORTE|DOM PEDRO|FORTUNA|GONCALVES DIAS|GOV. ARCHER|GOV. EUGENIO BARROS|GOV. LUIS ROCHA|GOVERNADOR ARCHER|GOVERNADOR EUGENIO BARROS|GOVERNADOR LUIZ ROCHA|GRACA ARANHA|JOSELANDIA|PRESIDENTE DUTRA|SANTA FILOMENA|SANTA FILOMENA DO MARANHAO|SANTO ANTONIO DOS LOPES|SAO DOMINGOS DO MARANHAO|SAO JOSE DOS BASILIOS|SENADOR ALEXANDRE COSTA|TUNTUM'),
('TIMON','MACROREGIÃO LESTE','MATOES|PARNARAMA|SAO FRANCISCO DO MARANHAO|TIMON')
), m AS (
  SELECT r.reg, r.macro, trim(mun) AS mun
  FROM r, unnest(string_to_array(r.muns, '|')) AS mun
)
UPDATE public.meningite_cases c
SET regional = m.reg, macroregiao = m.macro
FROM m
WHERE m.mun = translate(upper(btrim(c.municipio_residencia)), 'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑ', 'AAAAAEEEEIIIIOOOOOUUUUCN')
  AND (c.regional IS NULL OR c.macroregiao IS NULL);